-- 9-ELEVEN Private Digital Hub
-- Run this entire file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'visitor' check (role in ('admin','visitor')),
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_codes (
  id bigint generated by default as identity primary key,
  code_hash text not null,
  label text default 'Visitor',
  active boolean not null default true,
  expires_at timestamptz,
  max_uses integer,
  use_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.visitor_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  code_id bigint references public.visitor_codes(id) on delete set null,
  granted_at timestamptz not null default now()
);

create table if not exists public.content (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null check (category in ('image','video','audio','document','apk')),
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint default 0,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create index if not exists content_category_idx on public.content(category);
create index if not exists content_created_at_idx on public.content(created_at desc);

alter table public.profiles enable row level security;
alter table public.visitor_codes enable row level security;
alter table public.visitor_access enable row level security;
alter table public.content enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

create or replace function public.has_visitor_access()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1
    from public.visitor_access va
    where va.user_id = auth.uid()
      and exists(
        select 1 from public.visitor_codes vc
        where vc.id = va.code_id
          and vc.active = true
          and (vc.expires_at is null or vc.expires_at > now())
          and (vc.max_uses is null or vc.use_count <= vc.max_uses)
      )
  );
$$;

-- Verify a temporary visitor code and grant access to the current anonymous user.
create or replace function public.verify_visitor_code(input_code text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code public.visitor_codes%rowtype;
begin
  if auth.uid() is null then
    return json_build_object('ok', false, 'message', 'No authenticated session.');
  end if;

  select * into v_code
  from public.visitor_codes
  where active = true
    and (expires_at is null or expires_at > now())
    and (max_uses is null or use_count < max_uses)
    and code_hash = crypt(input_code, code_hash)
  order by created_at desc
  limit 1
  for update;

  if not found then
    return json_build_object('ok', false, 'message', 'Invalid or expired access code.');
  end if;

  insert into public.visitor_access(user_id, code_id)
  values(auth.uid(), v_code.id)
  on conflict (user_id) do update set code_id = excluded.code_id, granted_at = now();

  update public.visitor_codes
  set use_count = use_count + 1
  where id = v_code.id;

  return json_build_object('ok', true, 'label', v_code.label);
end;
$$;

-- Admin creates a code. Plain code is accepted over HTTPS and stored only as a hash.
create or replace function public.create_visitor_code(
  input_code text,
  input_label text default 'Visitor',
  input_expires_at timestamptz default null,
  input_max_uses integer default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare new_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;
  if length(trim(input_code)) < 6 then
    raise exception 'Code must be at least 6 characters';
  end if;
  insert into public.visitor_codes(code_hash,label,expires_at,max_uses)
  values(crypt(input_code, gen_salt('bf')), input_label, input_expires_at, input_max_uses)
  returning id into new_id;
  return new_id;
end;
$$;

create or replace function public.toggle_visitor_code(input_id bigint, input_active boolean)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'Admin only'; end if;
  update public.visitor_codes set active=input_active where id=input_id;
  return true;
end;
$$;

grant execute on function public.verify_visitor_code(text) to authenticated;
grant execute on function public.create_visitor_code(text,text,timestamptz,integer) to authenticated;
grant execute on function public.toggle_visitor_code(bigint,boolean) to authenticated;

-- Profiles: only the owner/admin row is readable by itself.
create policy "profiles_self" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles_admin_update" on public.profiles for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "profiles_admin_insert" on public.profiles for insert to authenticated with check (public.is_admin() or id = auth.uid());

-- Visitor code list is admin-only.
create policy "visitor_codes_admin_select" on public.visitor_codes for select to authenticated using (public.is_admin());

-- Visitor access can be read only for current user/admin.
create policy "visitor_access_self" on public.visitor_access for select to authenticated using (user_id = auth.uid() or public.is_admin());

-- Content is readable by an authorized visitor or admin.
create policy "content_read_authorized" on public.content for select to authenticated using (public.is_admin() or public.has_visitor_access());
create policy "content_admin_insert" on public.content for insert to authenticated with check (public.is_admin());
create policy "content_admin_update" on public.content for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "content_admin_delete" on public.content for delete to authenticated using (public.is_admin());

-- Private Storage bucket.
insert into storage.buckets (id, name, public)
values ('media','media',false)
on conflict (id) do update set public=false;

create policy "media_select_authorized"
on storage.objects for select to authenticated
using (
  bucket_id='media' and (public.is_admin() or public.has_visitor_access())
);

create policy "media_insert_admin"
on storage.objects for insert to authenticated
with check (bucket_id='media' and public.is_admin());

create policy "media_update_admin"
on storage.objects for update to authenticated
using (bucket_id='media' and public.is_admin())
with check (bucket_id='media' and public.is_admin());

create policy "media_delete_admin"
on storage.objects for delete to authenticated
using (bucket_id='media' and public.is_admin());

-- Admin can see codes. The raw code is never stored.
